name: .NET CI/CD Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pull_request_job:
    name: Pull Request Job
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: frankhaugen/Workflows/.github/workflows/dotnet-pull-request.yml@main
    secrets: inherit
    
  merge_job:
    name: Merge Job
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: frankhaugen/Workflows/.github/workflows/dotnet-publish-preview.yml@main
    secrets: inherit
    
  release_job:
    name: Release Job
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    uses: frankhaugen/Workflows/.github/workflows/dotnet-publish-release.yml@main
    secrets: inherit
    
